---
- name: Apply OpenShift changes
  include_role:
    name: ar_os_seed
    tasks_from: apply
  vars:
    ar_os_seed_config_dest: "{{ _ar_osc_aspera_config_dest }}"
    ar_os_seed_openshift_login_url: "{{ ar_osc_aspera_openshift_login_url }}"
