---
- name: Ensure dest dir exists
  file:
    path: "{{ _ar_osc_aspera_config_dest_templates }}"
    state: directory

- name: Copy common templates
  include_role:
    name: ar_os_common
  vars:
    ar_os_common_dest: "{{ _ar_osc_aspera_config_dest_templates }}"

- name: Generate aspera sshd config
  template:
    src: sshd_config.j2
    dest: "{{ _ar_osc_aspera_sshd_config_file }}"

- set_fact:
    _ar_osc_aspera_image: "{{ ar_osc_aspera_instance.aspera_image | default(aspera_image) }}"

- set_fact:
    _ar_osc_aspera_conf_template: "aspera_hsts_conf.j2"
  when: '"hsts" in _ar_osc_aspera_image'

- set_fact:
    _ar_osc_aspera_conf_template: "aspera_hste_conf.j2"
  when: '"hste" in _ar_osc_aspera_image'

- name: Guard against invalid config
  fail:
    msg: "The Aspera image name must contain either 'hsts' or 'hste' depending on whether '{{ ar_osc_aspera_name }}' is a server or endpoint"
  when: '"hste" not in _ar_osc_aspera_image and "hsts" not in _ar_osc_aspera_image'

- name: Generate aspera config
  template:
    src: "{{ _ar_osc_aspera_conf_template }}"
    dest: "{{ _ar_osc_aspera_config_file }}"

- name: Copy launch script to common area
  copy:
    src: "{{ ar_osc_aspera_launch_script }}"
    dest: "{{ _ar_osc_aspera_launch_script }}"

- name: Copy rsyslog config to common area
  copy:
    src: "{{ ar_osc_aspera_rsyslog_config }}"
    dest: "{{ _ar_osc_aspera_rsyslog_config }}"

- name: Generate aspera seed files config map
  template:
    src: aspera-seed-files-cm.yml.j2
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-seed-files-cm.yml"

- name: Copy Aspera app template to working area
  template:
    src: "{{ ar_osc_aspera_k8s_template }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-k8s-template.yml"
