---
- name: Ensure docker build dirs exists
  file:
    path: "{{ _ar_osc_aspera_config_dest_docker }}/{{ item }}"
    state: directory
  with_items:
    - aspera_rhel7_base
    - aspera_base

- name: Generate the Dockerfile for Aspera Base
  template:
    src: dockerfile-aspera-base.j2
    dest: "{{ _ar_osc_aspera_config_dest_docker }}/aspera_base/Dockerfile"

- name: Generate the Dockerfile for Aspera RHEL7 Base
  template:
    src: dockerfile-generic-rpm.j2
    dest: "{{ _ar_osc_aspera_config_dest_docker }}/aspera_rhel7_base/Dockerfile"
  when: not ar_osc_aspera_have_rhel_subscription
