---
- debug:
    msg: "Including Docker commands (a2.8) for Ansible version {{ ansible_version.full }}"

- name: Build Aspera RHEL7 Base Image (with subscription)
  docker_image:
    build:
      pull: no
      path: "{{ role_path }}/docker/rhel-plus"
      args:
        packagelist: "{{ aspera_config_package_dependencies | join(' ') }}"
    name: "{{ _aspera_config_docker_registry_base }}/{{ aspera_config_rhel_base_image_name }}"
    tag: "{{ aspera_config_version }}"
    push: "{{ aspera_config_push_images }}"
    source: build
    force_source: yes
    force_tag: yes
  when: aspera_config_have_rhel_subscription

- name: Build Aspera RHEL7 Base Image (from rpms)
  docker_image:
    build:
      pull: no
      path: "{{ aspera_config_dest_docker }}/aspera_rhel7_base"
    name: "{{ _aspera_config_docker_registry_base }}/{{ aspera_config_rhel_base_image_name }}"
    tag: "{{ aspera_config_version }}"
    push: "{{ aspera_config_push_images }}"
    source: build
    force_source: yes
    force_tag: yes
  when: not aspera_config_have_rhel_subscription

- name: Tag Aspera RHEL7 Base Image in Local Repo as latest
  docker_image:
    name: "{{ _aspera_config_docker_registry_base }}/{{ aspera_config_rhel_base_image_name }}:{{ aspera_config_version }}"
    repository: "{{ aspera_config_rhel_base_image_name }}:latest"
    force_tag: yes
    source: local

- name: Build Aspera Base Image
  docker_image:
    build:
      pull: no
      path: "{{ aspera_config_dest_docker }}/aspera_base"
      args:
        username: aspera
        password: "{{ aspera_secrets.aspera_password }}"
    name: "{{ _aspera_config_docker_registry_base }}/aspera-base"
    tag: "{{ aspera_config_version }}"
    push: "{{ aspera_config_push_images }}"
    source: build
    force_source: yes
    force_tag: yes

- name: Tag Aspera Base Image in Local Repo as latest
  docker_image:
    name: "{{ _aspera_config_docker_registry_base }}/aspera-base:{{ aspera_config_version }}"
    repository: aspera-base:latest
    force_tag: yes
    source: local

- name: Build Aspera HSTE Docker Image
  docker_image:
    build:
      pull: no
      path: "{{ role_path }}/docker/hste"
      args:
        package_url: "{{ aspera_config_endpoint_package }}"
        username: aspera
    name: "{{ _aspera_config_docker_registry_base }}/aspera-hste"
    push: "{{ aspera_config_push_images }}"
    source: build
    force_source: yes
    force_tag: yes

- name: Build Aspera HSTS Docker Image
  docker_image:
    build:
      pull: no
      path: "{{ role_path }}/docker/hsts"
      args:
        package_url: "{{ aspera_config_server_package }}"
        username: aspera
    name: "{{ _aspera_config_docker_registry_base }}/aspera-hsts"
    push: "{{ aspera_config_push_images }}"
    source: build
    force_source: yes
    force_tag: yes

- debug: var=aspera_config_push_images