---
- debug:
    msg: "Including Docker commands (a2.7) for Ansible version {{ ansible_version.full }}"

- name: Build Aspera RHEL7 Base Image (with subscription)
  docker_image:
    pull: no
    path: "{{ role_path }}/docker/rhel-plus"
    name: "{{ _ar_osc_aspera_docker_registry_base }}/{{ ar_osc_aspera_rhel_base_image_name }}"
    buildargs:
      packagelist: "{{ ar_osc_aspera_package_dependencies | join(' ') }}"
    tag: "{{ ar_osc_aspera_version }}"
    push: false
    force: no
  when: ar_osc_aspera_have_rhel_subscription

- name: Build Aspera RHEL7 Base Image (from rpms)
  docker_image:
    pull: no
    path: "{{ _ar_osc_aspera_config_dest_docker }}/aspera_rhel7_base"
    name: "{{ _ar_osc_aspera_docker_registry_base }}/{{ ar_osc_aspera_rhel_base_image_name }}"
    tag: "{{ ar_osc_aspera_version }}"
    push: false
    force: no
  when: not ar_osc_aspera_have_rhel_subscription

- name: Tag Aspera RHEL7 Base Image in Local Repo as latest
  docker_image:
    name: "{{ _ar_osc_aspera_docker_registry_base }}/{{ ar_osc_aspera_rhel_base_image_name }}:{{ ar_osc_aspera_version }}"
    repository: "{{ ar_osc_aspera_rhel_base_image_name }}:latest"

- name: Build Aspera Base Image
  docker_image:
    pull: no
    path: "{{ _ar_osc_aspera_config_dest_docker }}/aspera_base"
    name: "{{ _ar_osc_aspera_docker_registry_base }}/aspera-base"
    buildargs:
      username: aspera
      password: "{{ aspera_secrets.aspera_password }}"
    tag: "{{ ar_osc_aspera_version }}"
    push: false
    force: no

- name: Tag Aspera Base Image in Local Repo as latest
  docker_image:
    name: "{{ _ar_osc_aspera_docker_registry_base }}/aspera-base:{{ ar_osc_aspera_version }}"
    repository: aspera-base:latest

- name: Build Aspera HSTE Docker Image
  docker_image:
    pull: no
    path: "{{ role_path }}/files/docker/hste"
    name: "{{ _ar_osc_aspera_docker_registry_base }}/aspera-hste"
    buildargs:
      package_url: "{{ ar_osc_aspera_endpoint_package }}"
      username: aspera
    tag: "{{ ar_osc_aspera_version }}"
    push: "{{ ar_osc_aspera_push_images }}"
    force: no

- name: Build Aspera HSTS Docker Image
  docker_image:
    pull: no
    path: "{{ role_path }}/files/docker/hsts"
    name: "{{ _ar_osc_aspera_docker_registry_base }}/aspera-hsts"
    buildargs:
      package_url: "{{ ar_osc_aspera_server_package }}"
      username: aspera
    tag: "{{ ar_osc_aspera_version }}"
    push: "{{ ar_osc_aspera_push_images }}"
    force: no

- debug: var=ar_osc_aspera_push_images