---
- name: Build Docker Images
  include_tasks: docker.yml
  tags:
    - docker

- name: Generate Config
  include_tasks: config.yml
    - config

- name: Create load config for secrets
  include_tasks: secrets.yml
  tags:
    - secrets

- name: Include openshift-applier role
  include_role:
    name: roles/openshift-applier/roles/openshift-applier
    - apply

#- name: Setup Service Accounts
#  include_tasks: service-accounts.yml
#
#- name: Include openshift-applier role
#  include_role:
#    name: roles/openshift-applier/roles/openshift-applier
#
#- name: Remove load config for secrets
#  include_tasks: secrets.yml
#  tags:
#    - rmsecrets
