---
- name: Remove generated secrets for Aspera
  file:
    path: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-secrets.yml"
    state: absent
  changed_when: false

- name: Remove copied license file
  file:
    path: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-license"
    state: absent
  changed_when: false
