---
- name: Copy license file used to common area
  copy:
    src: "{{ ar_osc_aspera_license_file }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-license"
  changed_when: false

- name: Copy key to common area
  copy:
    content: "{{ aspera_secrets.aspera_key }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera_id_rsa"
    mode: 0660
  changed_when: false

- name: Copy pub key to common area
  copy:
    content: "{{ aspera_secrets.aspera_pub }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera_id_rsa.pub"
    mode: 0660
  changed_when: false

- name: Generate Aspera secrets template
  template:
    src: aspera-secrets.yml.j2
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-secrets.yml"
  changed_when: false
