---
- name: Generate Aspera secrets template
  template:
    src: aspera-seed-files-cm.yml.j2
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-seed-files-cm.yml"
  changed_when: false # Secret files are temporary and will be removed, so this would always represent a change
