---
- name: Copy license file used to common area
  copy:
    src: "{{ ar_osc_aspera_license_file }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-license"
  changed_when: false

- name: Generate Aspera secrets template
  template:
    src: aspera-secrets.yml.j2
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-secrets.yml"
  changed_when: false
