---
- debug: var=_ar_osc_aspera_config_dest_templates
- name: Generate Aspera secrets template
  template:
    src: aspera-seed-files-cm.yml.j2
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-seed-files-cm.yml"
  changed_when: false # Secret files are temporary and will be removed, so this would always represent a change

- name: Copy license file used to common area
  copy:
    src: "{{ ar_osc_aspera_license_file }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera-license"
  changed_when: false

- name: Copy key to common area
  copy:
    content: "{{ aspera_secrets.aspera_key }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera_id_rsa"
    mode: 0660
  changed_when: false

- name: Copy pub key to common area
  copy:
    content: "{{ aspera_secrets.aspera_pub }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/aspera_id_rsa.pub"
    mode: 0660
  changed_when: false

- name: Copy launch script to common area
  copy:
    src: "{{ ar_osc_aspera_launch_script }}"
    dest: "{{ _ar_osc_aspera_config_dest_templates }}/launch.sh"
  changed_when: false
