---
- name: Generate Aspera secrets template
  template:
    src: aspera-seed-files-cm.yml.j2
    dest: "{{ aspera_config_dest_templates }}/aspera-seed-files-cm.yml"
  changed_when: false # Secret files are temporary and will be removed, so this would always represent a change
  tags:
    - secrets

- name: Remove generated secrets for Aspera
  file:
    path: "{{ aspera_config_dest_templates }}/aspera-seed-files-cm.yml"
    state: absent
  changed_when: false
  tags:
    - rmsecrets
