---
- name: Check if Aspera Service Account exists
  shell: oc get sa aspera-sa -n {{ aspera_config_namespace }}
  register: aspera_sa
  changed_when: false
  failed_when: false

- name: Create the Aspera service account
  shell: oc create serviceaccount aspera-sa -n {{ aspera_config_namespace }}
  when: aspera_sa.rc != 0

- name: Assign the 'anyuid' privileges
  shell: oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ aspera_config_namespace }}:aspera-sa
  changed_when: false # TODO - work out how to establish if this is already there.
  register: policy_assignment_result
