---
package_repository: "http://artifactory-oss-artifactory.t1.training.local/artifactory/dump"
aspera_git_repo: "https://github.com/westdart/aspera-docker.git"
aspera_git_repo_path: "docker"
aspera_config_server_package: "{{ package_repository }}/dummy-1-0.noarch.rpm"
aspera_config_endpoint_package: "{{ package_repository }}/dummy-1-0.noarch.rpm"
aspera_password: 'password'
docker_repo_name: 'docker-registry-default.t1.training.local'
docker_repo_namespace: 'openshift'
base_template: "{{ playbook_dir }}/../templates/build-config-template.yml"
template: "{{ playbook_dir }}/../templates/build-config-params-template.yml"

aspera_rhel7_base:
  NAME: "aspera-rhel7-base"
  BASE_IMAGE: "rhel:rhel7"
  SOURCE_REPO: "{{ aspera_git_repo }}"
  SOURCE_REPO_PATH: "{{ aspera_git_repo_path }}"
  VERSION: latest
  DESTINATION_REPO_NAME: "{{ docker_repo_name }}"
  DESTINATION_REPO_NAMESPACE: "{{ docker_repo_namespace }}"
  DESTINATION_IMAGE_NAME: "aspera-rhel7-base"
  DESTINATION_IMAGE_TAG: "latest"
  PUSH_SECRET: "docker-push-secret"

aspera_base:
  NAME: "aspera-base"
  BASE_IMAGE: "aspera-rhel7-base:latest"
  SOURCE_REPO: "{{ aspera_git_repo }}"
  SOURCE_REPO_PATH: "{{ aspera_git_repo_path }}"
  VERSION: latest
  BUILD_ARGS:
    - username: "aspera"
    - password: "{{ aspera_password }}"
  DESTINATION_REPO_NAME: "{{ docker_repo_name }}"
  DESTINATION_REPO_NAMESPACE: "{{ docker_repo_namespace }}"
  DESTINATION_IMAGE_NAME: "aspera-base"
  DESTINATION_IMAGE_TAG: "latest"
  PUSH_SECRET: "docker-push-secret"

aspera_hsts:
  NAME: aspera-hsts
  GIT_REPO: "{{ aspera_git_repo }}"
  GIT_REPO_PATH: "{{ aspera_git_repo_path }}"
  VERSION: latest
  BUILD_ARGS: [package_url: "{{ aspera_config_server_package }}"]

aspera_hste:
  NAME: aspera-hste
  GIT_REPO: "{{ aspera_git_repo }}"
  GIT_REPO_PATH: "{{ aspera_git_repo_path }}"
  VERSION: latest
  BUILD_ARGS: [package_url: "{{ aspera_config_endpoint_package }}"]

openshift_cluster_content:

- object: ImageStreams
  content:
  - name: Aspera RHEL7 Base Image Stream
    template: "{{ base_template }}"
    action: apply
    params_from_vars: "{{ aspera_rhel7_base }}"
    namespace: "{{ docker_repo_namespace }}"
    tags:
    - aspera
    - docker

- object: ImageStreams
  content:
  - name: Aspera Base Image Stream
    template: "{{ template }}"
    action: apply
    params_from_vars: "{{ aspera_base }}"

#- object: ImageStreams
#  content:
#  - name: Aspera Server Image Stream
#    template: "{{ template }}"
#    action: create
#    params_from_vars: "{{ aspera_hsts }}"
#
#- object: ImageStreams
#  content:
#  - name: Aspera RHEL7 Base Image Stream
#    template: "{{ template }}"
#    action: create
#    params_from_vars: "{{ aspera_hste }}"
