FROM {{ ar_osc_aspera_rhel_base_image_name }}:{{ ar_osc_aspera_image_rhel_version }}

ARG username
ARG password

{#
To enable root access and therefore run debug tools within the container add the following line:
 && echo Welcome1 | passwd --stdin root \
#}
RUN useradd -m --gid 0 --uid 10001 --comment "asperaUser"  $username \
 && echo Welcome1 | passwd --stdin root \
 && chmod u+s /usr/sbin/rsyslogd \
 && chmod 644 /var/log/messages \
 && usermod -s /bin/bash $username && echo "$username:$password" | chpasswd \
 && groupadd aspadmins \
 && usermod -a -G aspadmins $username \
 && mkdir -p /home/$username/.ssh /opt/aspera \
 && chown -R $username:root /home/$username/.ssh /opt/aspera \
 && chmod 700 /home/$username/.ssh /home/$username

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["sh","/mnt/aspera/seed/launch.sh"]
